# Generated by Django 4.2.11 on 2025-04-03 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20191030_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=20000)),
                ('from_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_who', to='accounts.signal_user_profile')),
                ('to_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_where', to='accounts.signal_user_profile')),
            ],
        ),
    ]
