# Generated by Django 2.2.4 on 2019-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headedurl',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='img_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
