# Generated by Django 2.2.4 on 2019-12-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20191208_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.CharField(default='https://ikman.lk/', max_length=5000),
        ),
    ]
