# Generated by Django 2.2.4 on 2019-12-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20191208_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPageNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page_number', models.IntegerField()),
            ],
        ),
    ]
