# Generated by Django 2.2.4 on 2019-12-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yttrending',
            name='thumbnail_url',
            field=models.CharField(max_length=500),
        ),
    ]
