# Generated by Django 2.2.4 on 2019-12-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20191207_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yttrending',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
