# Generated by Django 2.2.4 on 2019-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20191207_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='thumbnail_url',
            field=models.CharField(max_length=500),
        ),
    ]
