# Generated by Django 2.2.4 on 2019-12-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20191207_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_value', models.IntegerField()),
            ],
        ),
    ]
