# Generated by Django 2.2.4 on 2019-12-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_statusobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusobject',
            name='rupee_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
