# Generated by Django 2.2.4 on 2019-12-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_statusobject_rupee_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusobject',
            name='population',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
