# Generated by Django 2.2.4 on 2019-12-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_statusobject_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='content',
        ),
    ]
